//! YAML string codec helpers.
//!
//! The CLI layer wraps the typed-model serde calls with file I/O and a
//! `# yaml-language-server: $schema=...` header so editors auto-validate
//! against the JSON Schemas in `schemas/` (generated by `re202 schema`).

#![allow(dead_code)]

/// YAML header for a serialized `SystemArea`. Editors that respect the
/// `yaml-language-server` comment will pick up the schema and validate
/// the document against it.
pub const SYSTEM_YAML_HEADER: &str =
    "# yaml-language-server: $schema=./schemas/re202-system.schema.json";

/// YAML header for a serialized `Memory`.
pub const MEMORY_YAML_HEADER: &str =
    "# yaml-language-server: $schema=./schemas/re202-memory.schema.json";
