//! YAML string codec helpers.
//!
//! The CLI layer wraps these with file I/O and a `# yaml-language-server:
//! $schema=...` header so editors auto-validate against the JSON Schemas in
//! `schemas/` (generated by `re202 schema`). The string codec lives here so
//! the wasm crate can use it without dragging in `Path`.

use crate::codec::CodecError;
use crate::memory::Memory;
use crate::system::SystemArea;

/// YAML header for a serialized `SystemArea`. Editors that respect the
/// `yaml-language-server` comment will pick up the schema and validate
/// the document against it.
pub const SYSTEM_YAML_HEADER: &str =
    "# yaml-language-server: $schema=./schemas/re202-system.schema.json";

/// YAML header for a serialized `Memory`.
pub const MEMORY_YAML_HEADER: &str =
    "# yaml-language-server: $schema=./schemas/re202-memory.schema.json";

pub fn memory_to_yaml_string(m: &Memory) -> Result<String, CodecError> {
    serde_yaml::to_string(m).map_err(|e| CodecError::Yaml(e.to_string()))
}

pub fn memory_from_yaml_str(s: &str) -> Result<Memory, CodecError> {
    serde_yaml::from_str(s).map_err(|e| CodecError::Yaml(e.to_string()))
}

pub fn system_to_yaml_string(s: &SystemArea) -> Result<String, CodecError> {
    serde_yaml::to_string(s).map_err(|e| CodecError::Yaml(e.to_string()))
}

pub fn system_from_yaml_str(text: &str) -> Result<SystemArea, CodecError> {
    serde_yaml::from_str(text).map_err(|e| CodecError::Yaml(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn memory_round_trip_default() {
        // Use a memory with predictable defaults round-tripping through YAML
        // and back to bytes — same fixture as the byte-level round-trip test.
        const MEMORY_1_PAYLOAD: [u8; 33] = [
            0x00, 0x04, 0x4D, 0x4D, 0x4D, 0x36, 0x36, 0x36, 0x60, 0x3F, 0x7F, 0x3F, 0x3F, 0x3F,
            0x3E, 0x3E, 0x3E, 0x06, 0x06, 0x06, 0x00, 0x00, 0x00, 0x52, 0x52, 0x52, 0x01, 0x00,
            0x00, 0x01, 0x0F, 0x04, 0x00,
        ];
        let m = Memory::from_bytes(&MEMORY_1_PAYLOAD).unwrap();
        let y = memory_to_yaml_string(&m).unwrap();
        let back: Memory = memory_from_yaml_str(&y).unwrap();
        assert_eq!(m, back);
        assert_eq!(back.to_bytes().unwrap(), MEMORY_1_PAYLOAD);
    }

    #[test]
    fn system_round_trip_default() {
        const SYSTEM_PAYLOAD: [u8; 18] = [
            0x00, 0x01, 0x01, 0x01, 0x00, 0x01, 0x00, 0x00, 0x04, 0x01, 0x11, 0x01, 0x01, 0x00,
            0x00, 0x00, 0x00, 0x01,
        ];
        let s = SystemArea::from_bytes(&SYSTEM_PAYLOAD).unwrap();
        let y = system_to_yaml_string(&s).unwrap();
        let back: SystemArea = system_from_yaml_str(&y).unwrap();
        assert_eq!(s, back);
        assert_eq!(back.to_bytes().unwrap(), SYSTEM_PAYLOAD);
    }

    #[test]
    fn from_yaml_returns_yaml_error_on_garbage() {
        let err = memory_from_yaml_str("not valid yaml: : :").unwrap_err();
        assert!(matches!(err, CodecError::Yaml(_)));
    }
}
